Adds flag to build_image to enable placing packages in the stateful partition
Review URL: http://codereview.chromium.org/859002

diff --git a/chromeos/scripts/build_image b/chromeos/scripts/build_image
--- a/chromeos/scripts/build_image
+++ b/chromeos/scripts/build_image
@@ -13,12 +13,12 @@
 # The path to common.sh should be relative to your script's location.
 . "$(dirname "$0")/common.sh"
 
-# Script must be run inside the chroot
+# Script must be run inside the chroot.
 assert_inside_chroot
 
 get_default_board
 
-# Flags
+# Flags.
 DEFINE_string board "$DEFAULT_BOARD" \
   "The board to build an image for."
 DEFINE_string build_root "/build" \
@@ -35,9 +35,10 @@ DEFINE_boolean installmask $FLAGS_TRUE \
   "Use INSTALL_MASK to shrink the resulting image."
 DEFINE_integer jobs -1 \
   "How many packages to build in parallel at maximum."
+DEFINE_boolean statefuldev $FLAGS_FALSE \
+  "Install development packages on stateful partition -- still experimental"
 
-
-# Parse command line
+# Parse command line.
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
@@ -50,11 +51,18 @@ if [ -z "$FLAGS_board" ] ; then
   exit 1
 fi
 
-# Determine build version
+# Sanity check: statefuldev cannot be true if withdev is false.
+if [ $FLAGS_statefuldev -eq $FLAGS_TRUE ] && 
+    [ $FLAGS_withdev -eq $FLAGS_FALSE ] ; then
+  echo "ERROR: statefuldev flag cannot be set to true without withdev"
+  exit 1
+fi
+
+# Determine build version.
 . "${SCRIPTS_DIR}/chromeos_version.sh"
 
-# Use canonical path since some tools (e.g. mount) do not like symlinks
-# Append build attempt to output directory
+# Use canonical path since some tools (e.g. mount) do not like symlinks.
+# Append build attempt to output directory.
 IMAGE_SUBDIR="${CHROMEOS_VERSION_STRING}-a${FLAGS_build_attempt}"
 OUTPUT_DIR="${FLAGS_output_root}/${FLAGS_board}/${IMAGE_SUBDIR}"
 ROOT_FS_DIR="${OUTPUT_DIR}/rootfs"
@@ -71,7 +79,7 @@ LOOP_DEV=
 . "${BOARD_ROOT}/etc/make.conf.board_setup"
 LIBC_VERSION=${LIBC_VERSION:-"2.10.1-r1"}
 
-# Figure out ARCH from the given toolchain
+# Figure out ARCH from the given toolchain.
 # TODO: Move to common.sh as a function after scripts are switched over.
 TC_ARCH=$(echo "$CHOST" | awk -F'-' '{ print $1 }')
 case "$TC_ARCH" in
@@ -86,12 +94,12 @@ case "$TC_ARCH" in
     exit 1
 esac
 
-# Hack to fix bug where x86_64 CHOST line gets incorrectly added
-# ToDo(msb): remove this hack
+# Hack to fix bug where x86_64 CHOST line gets incorrectly added.
+# ToDo(msb): remove this hack.
 PACKAGES_FILE="${BOARD_ROOT}/packages/Packages"
 sudo sed -e "s/CHOST: x86_64-pc-linux-gnu//" -i "${PACKAGES_FILE}"
 
-# Handle existing directory
+# Handle existing directory.
 if [[ -e "$OUTPUT_DIR" ]]; then
   if [[ $FLAGS_replace -eq $FLAGS_TRUE ]]; then
     sudo rm -rf "$OUTPUT_DIR"
@@ -103,18 +111,33 @@ if [[ -e "$OUTPUT_DIR" ]]; then
   fi
 fi
 
-# create the output directory
+# Create the output directory.
 mkdir -p "$OUTPUT_DIR"
 
 cleanup_rootfs_loop() {
   sudo umount "$LOOP_DEV"
-  sleep 1  # in case $LOOP_DEV is in use (TODO: Try umount -l?)
+  sleep 1  # in case $LOOP_DEV is in use (TODO: Try umount -l?).
   sudo losetup -d "$LOOP_DEV"
+}
+
+cleanup_stateful_fs_loop() {
+  sudo umount "$STATEFUL_LOOP_DEV"
+  sleep 1  # follows from cleanup_root_fs_loop.
+  sudo losetup -d "$STATEFUL_LOOP_DEV"
 }
 
 cleanup() {
   # Disable die on error.
   set +e
+
+  # Unmount stateful partition from usr/local if bound.
+  if [ -s "$ROOT_FS_DIR/usr/local/bin" ] ; then
+    sudo umount $ROOT_FS_DIR/usr/local
+  fi
+
+  if [[ -n "$STATEFUL_LOOP_DEV" ]]; then
+    cleanup_stateful_fs_loop
+  fi
 
   if [[ -n "$LOOP_DEV" ]]; then
     cleanup_rootfs_loop
@@ -123,33 +146,58 @@ cleanup() {
   # Turn die on error back on.
   set -e
 }
+
 trap cleanup EXIT
 
 mkdir -p "$ROOT_FS_DIR"
 
-# -- Create and format the root file system --
+# Create and format the root file system.
+
+# Check for loop device before creating image.
+LOOP_DEV=$(sudo losetup -f)
+if [ -z "$LOOP_DEV" ] ; then
+  echo "No free loop device.  Free up a loop device or reboot.  exiting. "
+  exit 1
+fi
 
 # Create root file system disk image to fit on a 1GB memory stick.
 # 1 GB in hard-drive-manufacturer-speak is 10^9, not 2^30.  950MB < 10^9 bytes.
 ROOT_SIZE_BYTES=$((1024 * 1024 * 640))
 dd if=/dev/zero of="$ROOT_FS_IMG" bs=1 count=1 seek=$((ROOT_SIZE_BYTES - 1))
-
-# Format, tune, and mount the rootfs.
-UUID=$(uuidgen)
-DISK_LABEL="C-KEYFOB"
-LOOP_DEV=$(sudo losetup -f)
 sudo losetup "$LOOP_DEV" "$ROOT_FS_IMG"
 sudo mkfs.ext3 "$LOOP_DEV"
+
+# Tune and mount rootfs.
+UUID=$(uuidgen)
+DISK_LABEL="C-KEYFOB"
 sudo tune2fs -L "$DISK_LABEL" -U "$UUID" -c 0 -i 0 "$LOOP_DEV"
 sudo mount "$LOOP_DEV" "$ROOT_FS_DIR"
 
-# -- Turn root file system into bootable image --
+# Create stateful partition of the same size as the rootfs.
+STATEFUL_IMG="$OUTPUT_DIR/stateful_partition.image"
+STATEFUL_DIR="$OUTPUT_DIR/stateful_partition"
+STATEFUL_LOOP_DEV=$(sudo losetup -f)
+if [ -z "$STATEFUL_LOOP_DEV" ] ; then
+  echo "No free loop device.  Free up a loop device or reboot.  exiting. "
+  exit 1
+fi
+dd if=/dev/zero of="$STATEFUL_IMG" bs=1 count=1 seek=$((ROOT_SIZE_BYTES - 1))
+sudo losetup "$STATEFUL_LOOP_DEV" "$STATEFUL_IMG"
+sudo mkfs.ext3 "$STATEFUL_LOOP_DEV"
+sudo tune2fs -L "C-STATE" -U "$UUID" -c 0 -i 0 \
+    "$STATEFUL_LOOP_DEV"
+
+# Mount the stateful partition.
+mkdir -p "$STATEFUL_DIR"
+sudo mount "$STATEFUL_LOOP_DEV" "$STATEFUL_DIR"
+
+# Turn root file system into bootable image.
 if [[ "$ARCH" = "x86" ]]; then
   # Setup extlinux configuration.
   # TODO: For some reason the /dev/disk/by-uuid is not being generated by udev
   # in the initramfs. When we figure that out, switch to root=UUID=$UUID.
   sudo mkdir -p "$ROOT_FS_DIR"/boot
-  # TODO(adlr): use initramfs for booting
+  # TODO(adlr): use initramfs for booting.
   cat <<EOF | sudo dd of="$ROOT_FS_DIR"/boot/extlinux.conf
 DEFAULT chromeos-usb
 PROMPT 0
@@ -194,6 +242,28 @@ if [[ $FLAGS_jobs -ne -1 ]]; then
   EMERGE_JOBS="--jobs=$FLAGS_jobs"
 fi
 
+if [ $FLAGS_statefuldev -eq $FLAGS_TRUE ] ; then
+  # Creating stateful partition.
+  echo "Setting up symlinks for stateful partition install"
+  DEV_IMAGE_ROOT="$STATEFUL_DIR/dev_image"
+  sudo mkdir -p "$DEV_IMAGE_ROOT/usr"
+  
+  # Setup symlinks in stateful partition.
+  for path in bin include lib libexec sbin share; do
+    sudo mkdir "$DEV_IMAGE_ROOT/$path"
+    sudo ln -s "$DEV_IMAGE_ROOT/$path" "$DEV_IMAGE_ROOT/usr/$path"
+  done
+   
+  # Setup symlinks that don't conform to above model.
+  sudo ln -s "$DEV_IMAGE_ROOT/lib" "$DEV_IMAGE_ROOT/usr/lib64"
+  sudo ln -s "$DEV_IMAGE_ROOT" "$DEV_IMAGE_ROOT/usr/local"
+
+  # Bind to rootfs.
+  echo "Binding stateful partition to rootfs's /usr/local"
+  sudo mkdir -p "$ROOT_FS_DIR/usr/local"
+  sudo mount -n --bind "$DEV_IMAGE_ROOT" "$ROOT_FS_DIR/usr/local"
+fi
+
 # We "emerge --root=$ROOT_FS_DIR --root-deps=rdeps --usepkgonly" all of the
 # runtime packages for chrome os. This builds up a chrome os image from binary
 # packages with runtime dependencies only.  We use INSTALL_MASK to trim the
@@ -201,10 +271,33 @@ fi
 sudo INSTALL_MASK="$INSTALL_MASK" emerge-${BOARD} \
   --root="$ROOT_FS_DIR" --root-deps=rdeps \
   --usepkgonly chromeos $EMERGE_JOBS
-if [[ $FLAGS_withdev -eq $FLAGS_TRUE ]]; then
+if [[ $FLAGS_withdev -eq $FLAGS_TRUE ]] ; then
+  # Determine the root dir for development packages
+  ROOT_DIR="$ROOT_FS_DIR"
+  [ $FLAGS_statefuldev -eq $FLAGS_TRUE ] && ROOT_DIR="$ROOT_FS_DIR/usr/local" 
+  
   sudo INSTALL_MASK="$INSTALL_MASK" emerge-${BOARD} \
-    --root="$ROOT_FS_DIR" --root-deps=rdeps \
-    --usepkgonly chromeos-dev $EMERGE_JOBS
+      --root="$ROOT_DIR" --root-deps=rdeps \
+      --usepkgonly chromeos-dev $EMERGE_JOBS
+ 
+  if [ $FLAGS_statefuldev -eq $FLAGS_TRUE ] ; then
+    # chromeos_startup checks file and mounts /usr/local if it exists.
+    sudo mkdir -p "$ROOTF_FS_DIR/root"
+    sudo touch "$ROOTFS_DIR/root/.dev_mode"
+ 
+    # Fix symlinks so they work on live system.
+    for path in bin include lib libexec sbin share; do
+      sudo unlink $DEV_IMAGE_ROOT/usr/$path
+      sudo ln -s /usr/local/$path $DEV_IMAGE_ROOT/usr/$path
+    done
+
+    # Fix exceptions.
+    sudo unlink "$DEV_IMAGE_ROOT/usr/lib64"
+    sudo unlink "$DEV_IMAGE_ROOT/usr/local"
+    
+    sudo ln -s "/usr/local/lib" "$DEV_IMAGE_ROOT/usr/lib64"
+    sudo ln -s "/usr/local" "$DEV_IMAGE_ROOT/usr/local"
+  fi 
 
   # The ldd tool is a useful shell script but lives in glibc; just copy it.
   sudo cp -a "$(which ldd)" "${ROOT_FS_DIR}/usr/bin"
@@ -215,17 +308,26 @@ WITH_DEV=""
 if [[ $FLAGS_withdev -eq $FLAGS_TRUE ]]; then
   WITH_DEV="--withdev"
 fi
+
+#TODO(sosa@chromium.org) - Does it make sense to leave /usr/local bound here?
 "${SCRIPTS_DIR}/customize_rootfs" \
   --root="$ROOT_FS_DIR" \
   --target="$ARCH" \
   --board="$BOARD" \
   $WITH_DEV
 
-# Check that the image has been correctly created
+# Check that the image has been correctly created.
 "${SCRIPTS_DIR}/test_image" \
   --root="$ROOT_FS_DIR" \
   --target="$ARCH"
 
+# Only bound if installing dev to stateful.
+if [ $FLAGS_statefuldev -eq $FLAGS_TRUE ] ; then
+  sudo umount "$ROOT_FS_DIR/usr/local"
+fi
+
+# Cleanup loop devices.
+cleanup_stateful_fs_loop
 cleanup_rootfs_loop
 
 # Create a master boot record.
