Cleanup remaining vestiges of customize_rootfs.
Also, some cleanup of the cros_set_lsb_release script.

BUG=chromium-os:4628
TEST=build_image, check /etc/lsb-release, ran suite_Smoke

Change-Id: I0f7e2e834be69aeca2c85cf726dfac04b06d3f12

Review URL: http://codereview.chromium.org/6604007

diff --git a/chromeos/scripts/cros_set_lsb_release b/chromeos/scripts/cros_set_lsb_release
--- a/chromeos/scripts/cros_set_lsb_release
+++ b/chromeos/scripts/cros_set_lsb_release
@@ -4,61 +4,31 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-# Script to set /etc/lsb-release on the root file system.
+# Script to set /etc/lsb-release on the root file system. This script is sourced
+# by build_image inside chroot.
 
-# --- BEGIN COMMON.SH BOILERPLATE ---
-# Load common CrOS utilities.  Inside the chroot this file is installed in
-# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
-# location.
-find_common_sh() {
-  local common_paths=(/usr/lib/crosutils $(dirname "$0"))
-  local path
+readonly COMMON_SH=/usr/lib/crosutils/common.sh
+if [ ! -r "${COMMON_SH}" ]; then
+  echo "ERROR: Run inside chroot."
+  exit 1
+fi
 
-  SCRIPT_ROOT=
-  for path in "${common_paths[@]}"; do
-    if [ -r "${path}/common.sh" ]; then
-      SCRIPT_ROOT=${path}
-      break
-    fi
-  done
-}
-
-find_common_sh
-. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
-# --- END COMMON.SH BOILERPLATE ---
-
-# Script must be run inside the chroot
-restart_in_chroot_if_needed "$@"
+. "${COMMON_SH}"
 
 # Flags
-DEFINE_string target "x86" \
-  "The target architecture to build for. One of { x86, arm }."
-DEFINE_string board ""      \
-  "The board to build an image for."
-DEFINE_string root ""      \
-  "The root file system to customize."
+DEFINE_string board "" "The board to build an image for."
+DEFINE_string root "" "The root file system to write /etc/lsb-release to."
 
 # Parse command line
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
-# Die on any errors.
 set -e
 
-. ${SRC_ROOT}/third_party/chromiumos-overlay/chromeos/config/chromeos_version.sh
-
 ROOT_FS_DIR="$FLAGS_root"
-if [[ -z "$ROOT_FS_DIR" ]]; then
-  echo "Error: --root is required."
-  exit 1
-fi
-if [[ ! -d "$ROOT_FS_DIR" ]]; then
-  echo "Error: Root FS does not exist? ($ROOT_FS_DIR)"
-  exit 1
-fi
-
-# TODO: Is this still necessary?
-sudo chmod 0755 "${ROOT_FS_DIR}/."
+[ -n "$ROOT_FS_DIR" ] || die "--root is required."
+[ -d "$ROOT_FS_DIR" ] || die "Root FS does not exist? ($ROOT_FS_DIR)"
+[ -n "${CHROMEOS_VERSION_STRING}" ] || die "chromeos_version.sh isn't sourced."
 
 # Write stock lsb-release file
 # Set CHROMEOS_VERSION_DESCRIPTION here (uses vars set in chromeos_version.sh)
