make_chroot: improve cooperation with cros_sdk
* Remove common.sh boilerplate, replace with just a make_chroot specific
code for the two paths where we expect it.

* Change outcome message to suggest usage of cros_sdk instead of
enter_chroot.

* Change SCRIPT_NAME if we're being called from cros_sdk.

BUG=chromium-os:18750
TEST=below
1) run it both by itself and from cros_sdk
2) run it from src/scripts and cros-overlay/chromeos/scripts/

Change-Id: Ide2e84b41e13b90297ec8c834d2c9e1ba5ee7cfe
Reviewed-on: http://gerrit.chromium.org/gerrit/5791
Tested-by: Zdenek Behan <zbehan@chromium.org>
Reviewed-by: David James <davidjames@chromium.org>
Reviewed-by: Anush Elangovan <anush@chromium.org>

diff --git a/chromeos/scripts/make_chroot b/chromeos/scripts/make_chroot
--- a/chromeos/scripts/make_chroot
+++ b/chromeos/scripts/make_chroot
@@ -9,26 +9,15 @@
 # setup for development. Once created, the password is set to PASSWORD (below).
 # One can enter the chrooted environment for work by running enter_chroot.sh.
 
-# --- BEGIN COMMON.SH BOILERPLATE ---
-# Load common CrOS utilities.  Inside the chroot this file is installed in
-# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
-# location.
-find_common_sh() {
-  local common_paths=(/usr/lib/crosutils $(dirname "$0"))
-  local path
-
-  SCRIPT_ROOT=
-  for path in "${common_paths[@]}"; do
-    if [ -r "${path}/common.sh" ]; then
-      SCRIPT_ROOT=${path}
-      break
-    fi
-  done
-}
-
-find_common_sh
-. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
-# --- END COMMON.SH BOILERPLATE ---
+# Find common.sh, because this script can run from two locations:
+# src/scripts/ or src/third_party/chromiumos-overlay/chromeos/scripts
+for path in "$(dirname $0)" "$(dirname $0)/../../../../scripts"; do
+  if [ -r "${path}/common.sh" ]; then
+    SCRIPT_ROOT=${path}
+    break
+  fi
+done
+. "${SCRIPT_ROOT}/common.sh" || { echo "Unable to load common.sh"; exit 1; }
 
 # Check if the host machine architecture is supported.
 ARCHITECTURE="$(uname -m)"
@@ -54,12 +43,18 @@ DEFINE_string stage3_date "2010.03.09" \
   "Use the stage3 with the given date."
 DEFINE_string stage3_path "" \
   "Use the stage3 located on this path."
+DEFINE_boolean cros_sdk $FLAGS_FALSE "Internal: we're called from cros_sdk"
 
 # Parse command line flags
 FLAGS_HELP="usage: $SCRIPT_NAME [flags]"
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 check_flags_only_and_allow_null_arg "$@" && set --
+
+if [ "${FLAGS_cros_sdk}" == "${FLAGS_TRUE}" ]; then
+  # HACK: If we're being called by cros_sdk, change the messages.
+  SCRIPT_NAME=cros_sdk
+fi
 
 assert_not_root_user
 # Set the right umask for chroot creation.
@@ -422,9 +417,9 @@ print_time_elapsed
 
 echo
 echo "$SCRIPT_NAME: All set up.  To enter the chroot, run:"
-echo "$SCRIPT_NAME: $ $SCRIPTS_DIR/enter_chroot.sh $CHROOT_EXAMPLE_OPT"
+echo "$SCRIPT_NAME: $ cros_sdk --enter $CHROOT_EXAMPLE_OPT"
 echo ""
 echo "CAUTION: Do *NOT* rm -rf the chroot directory; if there are stale bind"
 echo "mounts you may end up deleting your source tree too.  To unmount and"
 echo "delete the chroot cleanly, use:"
-echo "$ $0 --delete $CHROOT_EXAMPLE_OPT"
+echo "$ $SCRIPT_NAME --delete $CHROOT_EXAMPLE_OPT"
