Verify that SCRIPTS_DIR exists in build_packages and setup_board.
This hack is necessary for old chroots to ensure that we source a good
common.sh when the one inside the chroot is out of date. We'll be able
to get rid of this after everybody has updated their chroot to have a working
version of common.sh and/or we have deprecated running scripts from the
source directory.

Also fix logic for when common.sh is missing to exit properly.

BUG=chromium-os:11598
TEST=Verify that build_packages and setup_board still work when
     old common.sh is present in chroot.

Change-Id: I88431decb50ee17c239d081fa0cc6873685b19e4

Review URL: http://codereview.chromium.org/6334076

diff --git a/chromeos/scripts/setup_board b/chromeos/scripts/setup_board
--- a/chromeos/scripts/setup_board
+++ b/chromeos/scripts/setup_board
@@ -6,7 +6,6 @@
 
 # This script sets up a the sysroot for a particular target board.
 
-# --- BEGIN COMMON.SH BOILERPLATE ---
 # Load common CrOS utilities.  Inside the chroot this file is installed in
 # /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
 # location.
@@ -16,7 +15,8 @@ find_common_sh() {
 
   SCRIPT_ROOT=
   for path in "${common_paths[@]}"; do
-    if [ -r "${path}/common.sh" ]; then
+    local common="${path}/common.sh"
+    if ([ -r "${common}" ] && . "${common}" && [ -d "${SCRIPTS_DIR}" ]); then
       SCRIPT_ROOT=${path}
       break
     fi
@@ -24,8 +24,7 @@ find_common_sh() {
 }
 
 find_common_sh
-. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
-# --- END COMMON.SH BOILERPLATE ---
+. "${SCRIPT_ROOT}/common.sh" || ! echo "Unable to load common.sh" || exit 1
 
 # Script must run inside the chroot
 restart_in_chroot_if_needed "$@"
