Update setup_board to handle multiple installed versions of gcc.
Also add more diagnostics in case we find multiple versions of a toolchain
package or are missing a needed toolchain package.

BUG=chromium-os:16482
TEST=Test that right version of gcc is picked if two are installed.
Change-Id: Iee5ad4380a9e9da44b58d4c3f557dcf2d937e917
Reviewed-on: http://gerrit.chromium.org/gerrit/2582
Tested-by: David James <davidjames@chromium.org>
Reviewed-by: David James <davidjames@chromium.org>

diff --git a/chromeos/scripts/setup_board b/chromeos/scripts/setup_board
--- a/chromeos/scripts/setup_board
+++ b/chromeos/scripts/setup_board
@@ -177,29 +177,53 @@ build_toolchain() {
 
 # Get the version number of a toolchain package.
 cross_get_version() {
-  local pkg=cross-$FLAGS_toolchain/$1
-  local pkg_ver=$(portageq match / $pkg || true)
-  echo ${pkg_ver/$pkg-}
+  local pkg="$1"
+  local cp=cross-$FLAGS_toolchain/$pkg
+  local atom=$cp
+  if [ "$pkg" = "gcc" ]; then
+    # Users can install multiple versions of gcc at once, so we need to call
+    # gcc-config to find out which installed version is selected.
+    local executable="$(CTARGET=$FLAGS_toolchain gcc-config -c || true)"
+    local ver_norev="${executable/$FLAGS_toolchain-}"
+    if [ -n "$ver_norev" ]; then
+      atom="~cross-$FLAGS_toolchain/$pkg-$ver_norev"
+    fi
+  fi
+  local cpv="$(portageq match / $atom)"
+  count="$(echo $cpv | grep "^$cp-" | wc -w)"
+  if [ "$count" -gt "1" ]; then
+    die "Multiple versions of $atom installed"
+  elif [ "$count" -lt "1" ]; then
+    die "Cannot find $atom"
+  fi
+  echo ${cpv/$cp-}
 }
 
 install_toolchain_in_provided() {
+  local binutils_ver="$1"
+  local gcc_ver="$2"
+  local glibc_ver="$3"
   # Tell portage that toolchain packages are already installed in the sysroot.
   (
-    echo sys-devel/binutils-$(cross_get_version binutils)
-    echo sys-devel/gcc-$(cross_get_version gcc)
-    echo sys-libs/glibc-$(cross_get_version glibc)
+    echo sys-devel/binutils-$binutils_ver
+    echo sys-devel/gcc-$gcc_ver
+    echo sys-libs/glibc-$glibc_ver
   ) | sudo_clobber "$BOARD_PROFILE/package.provided"
 }
 
 # Install all of the stuff that depends on the toolchain versions
 # into the board root.
 install_toolchain_in_board() {
-  local libc_version=$(cross_get_version glibc)
-  local gcc_version=$(cross_get_version gcc)
+  local binutils_ver=$(cross_get_version binutils)
+  local gcc_ver=$(cross_get_version gcc)
+  local libc_ver=$(cross_get_version glibc)
+  if [[ -z "$binutils_ver" || -z "$gcc_ver" || -z "$libc_ver" ]]; then
+    die "Cannot find toolchain to install into board root"
+  fi
   echo "Installing the toolchain into the board root."
   # Untar glibc to get most of the headers required to build.
   PKGDIR=$(portageq envvar PKGDIR)
-  LIBC_TAR="glibc-${libc_version}.tbz2"
+  LIBC_TAR="glibc-${libc_ver}.tbz2"
   LIBC_PATH="${PKGDIR}/cross-${FLAGS_toolchain}/${LIBC_TAR}"
 
   # Install libc libraries.
@@ -214,14 +238,14 @@ install_toolchain_in_board() {
 
   # We need to install libstdc++ manually from the cross toolchain.
   # TODO: Figure out a better way of doing this?
-  GCC_FILES=$(portageq contents / cross-${FLAGS_toolchain}/gcc-$gcc_version)
+  GCC_FILES=$(portageq contents / cross-${FLAGS_toolchain}/gcc-$gcc_ver)
   LIBGCC_FILE=$(echo "${GCC_FILES}" | grep libgcc_s.so$ | head -n1)
   LIBSTDCXX_FILE=$(echo "${GCC_FILES}" | grep libstdc++.so$ | head -n1)
 
   if [[ -z "$LIBGCC_FILE" || -z "$LIBSTDCXX_FILE" ]]
   then
     error "Could not find libgcc_s.so/libstdc++_s.so. Is
-           =cross-$FLAGS_toolchain/gcc-$gcc_version
+           =cross-$FLAGS_toolchain/gcc-$gcc_ver
            emerged properly?"
     exit 1
   else
@@ -237,11 +261,11 @@ install_toolchain_in_board() {
   sudo cp -a /usr/include/rpcsvc/nfs_prot.h "${BOARD_ROOT}/usr/include/rpcsvc"
   sudo cp -a /usr/include/rpcsvc/yppasswd.h "${BOARD_ROOT}/usr/include/rpcsvc"
 
-  install_toolchain_in_provided
+  install_toolchain_in_provided "$binutils_ver" "$gcc_ver" "$libc_ver"
 
   # Configure new libc version in make.conf.board_setup.
   sudo sed -i -e "/^LIBC_VERSION=/d" $BOARD_SETUP
-  echo "LIBC_VERSION=\"$libc_version\"" | sudo_append $BOARD_SETUP
+  echo "LIBC_VERSION=\"$libc_ver\"" | sudo_append $BOARD_SETUP
 }
 
 # Parse command line flags
