Added behaviour to setup_board to automatically update the toolchain if it is needed. This will occur whether or not the user has an existing board, and whether or not they do --force to clobber their board.
BUG=chromium-os:6014
TEST=Ran setup_board with different toolchain versions and checked to see if update would occur. Did this with and without an existing board.

Review URL: http://codereview.chromium.org/6060004

Change-Id: I4ca5202c27d0e24b2c8514303ca80ea630e9193a

diff --git a/chromeos/scripts/setup_board b/chromeos/scripts/setup_board
--- a/chromeos/scripts/setup_board
+++ b/chromeos/scripts/setup_board
@@ -45,8 +45,27 @@ DEFINE_string profile "" \
   "The portage configuration profile to use. Profile must be located in overlay-board/profiles"
 
 
+tc_pkg_needs_update() {
+  CURRENT_VERSION=$(equery l cross-${FLAGS_toolchain}/* | grep $1 | \
+    cut -d '/' -f 2 | cut -d '-' -f 2-)
+  eval NEW_VERSION="\${FLAGS_${1}_version}"
+  if [ "${CURRENT_VERSION}" == "${NEW_VERSION}" ]; then
+    echo ${FLAGS_FALSE}
+  else
+    echo ${FLAGS_TRUE}
+  fi
+}
+
+uninstall_toolchain() {
+  echo "Uninstalling the toolchain."
+  # Even if the uninstall fails, keep going. It's likely
+  # that it didn't exist in the first place.
+  sudo crossdev -v -C $FLAGS_toolchain || true
+}
+
 # Build the toolchain with crossdev.
 build_toolchain() {
+  echo "Building the toolchain."
   # TODO(davidjames): Fix uploading of cross prebuilts so that we don't have
   #                   to use the old location to get the cross prebuilts.
   #BINHOST=$(portageq envvar PORTAGE_BINHOST)
@@ -76,11 +95,27 @@ build_toolchain() {
       $CROSS_KERNEL   \
       $CROSS_LIBC     \
       $CROSS_USEPKG
+
+  # Set up toolchain wrappers to force $SYSROOT and perform sanity checks.
+  GCC_PROFILE="${FLAGS_toolchain}-${GCC_VERSION}"
+  GCC_BIN_PATH=$(gcc-config --get-bin-path "$GCC_PROFILE")
+  CCACHE_BIN=$(which ccache || true)
+  for i in c++ cpp g++ gcc gfortran ; do
+    GCC_BINARY="${GCC_BIN_PATH}/$FLAGS_toolchain-${i}"
+    if [ ! -L "${GCC_BINARY}" ] ; then
+      sudo mv "${GCC_BINARY}" "${GCC_BINARY}.real"
+      sudo ln -s "${SCRIPTS_DIR}/sysroot_wrapper" "${GCC_BINARY}"
+    fi
+    if [ -f "${CCACHE_BIN}" ]; then
+      sudo ln -sf "${CCACHE_BIN}" "/usr/lib/ccache/bin/${FLAGS_toolchain}-${i}"
+    fi
+  done
 }
 
 # Install all of the stuff that depends on the toolchain versions
 # into the board root.
 install_toolchain_in_board() {
+  echo "Installing the toolchain into the board root."
   #
   # Untar glibc to get most of the headers required to build.
   #
@@ -129,20 +164,6 @@ if [ -z "$FLAGS_board" ] ; then
 fi
 
 get_board_and_variant $FLAGS_board $FLAGS_variant
-
-BOARD_ROOT="${FLAGS_build_root}/${BOARD_VARIANT}"
-if [ -d "$BOARD_ROOT" ] ; then
-  if [[ $FLAGS_force -eq $FLAGS_TRUE ]]; then
-    echo "--force set.  Re-creating $BOARD_ROOT..."
-    # Removal takes long. Make it asynchronous.
-    TEMP_DIR=`mktemp -d`
-    sudo mv $BOARD_ROOT $TEMP_DIR
-    sudo rm -rf $TEMP_DIR &
-  else
-    error "Board output directory '$BOARD_ROOT' already exists."
-    exit 1
-  fi
-fi
 
 #
 # Construct board overlay list.
@@ -217,25 +238,45 @@ if [ -z $FLAGS_gcc_version ]; then
   fi
 fi
 
-build_toolchain
+# Locations we will need
+BOARD_ROOT="${FLAGS_build_root}/${BOARD_VARIANT}"
+CHROMIUMOS_OVERLAY="/usr/local/portage/chromiumos/"
+CHROMIUMOS_CONFIG="${CHROMIUMOS_OVERLAY}/chromeos/config"
+CHROMIUMOS_PROFILES="${CHROMIUMOS_OVERLAY}/profiles"
+BOARD_ETC="${BOARD_ROOT}/etc"
+BOARD_PROFILE="${BOARD_ETC}/portage/profile"
+
+# Version of GCC we will be installing, without the ebuild revision number.
+GCC_VERSION=`echo ${FLAGS_gcc_version} | sed -e 's/\-r[0-9]*$//g'`
+
+if [ "$(tc_pkg_needs_update "binutils")" = "$FLAGS_TRUE" ] ||
+  [ "$(tc_pkg_needs_update "gcc")" = "$FLAGS_TRUE" ] ||
+  [ "$(tc_pkg_needs_update "libc")" = "$FLAGS_TRUE" ]; then
+  warn "Toolchain needs to be updated! Updating toolchain..."
+  uninstall_toolchain
+  build_toolchain
+  # If the board root already exists, re-install the toolchain there.
+  if [ -d "$BOARD_ROOT" ] && [ "$FLAGS_force" = "$FLAGS_FALSE" ]; then
+    install_toolchain_in_board
+  fi
+fi
+
+if [ -d "$BOARD_ROOT" ] ; then
+  if [[ $FLAGS_force -eq $FLAGS_TRUE ]]; then
+    echo "--force set.  Re-creating $BOARD_ROOT..."
+    # Removal takes long. Make it asynchronous.
+    TEMP_DIR=`mktemp -d`
+    sudo mv $BOARD_ROOT $TEMP_DIR
+    sudo rm -rf $TEMP_DIR &
+  else
+    warn "Board output directory '$BOARD_ROOT' already exists."
+    warn "Not setting up board root. "
+    warn "Use --force to clobber the board root and start again."
+    exit 1
+  fi
+fi
 
 sudo mkdir -p "$BOARD_ROOT"
-
-# Set up toolchain wrappers to force $SYSROOT and perform sanity checks.
-GCC_VERSION=`echo ${FLAGS_gcc_version} | sed -e 's/\-r[0-9]*$//g'`
-GCC_PROFILE="${FLAGS_toolchain}-${GCC_VERSION}"
-GCC_BIN_PATH=$(gcc-config --get-bin-path "$GCC_PROFILE")
-CCACHE_BIN=$(which ccache || true)
-for i in c++ cpp g++ gcc gfortran ; do
-  GCC_BINARY="${GCC_BIN_PATH}/$FLAGS_toolchain-${i}"
-  if [ ! -L "${GCC_BINARY}" ] ; then
-    sudo mv "${GCC_BINARY}" "${GCC_BINARY}.real"
-    sudo ln -s "${SCRIPTS_DIR}/sysroot_wrapper" "${GCC_BINARY}"
-  fi
-  if [ -f "${CCACHE_BIN}" ]; then
-    sudo ln -sf "${CCACHE_BIN}" "/usr/lib/ccache/bin/${FLAGS_toolchain}-${i}"
-  fi
-done
 
 # TODO(cmasone): Do this more cleanly, if we figure out what "cleanly" means.
 # Set up wrapper for pkg-config.  Point a board-specific wrapper at the
@@ -243,11 +284,6 @@ done
 sudo ln -sf "/usr/bin/cross-pkg-config" "/usr/bin/${FLAGS_toolchain}-pkg-config"
 
 # Setup make.conf and make.profile as symlinks to ones in revision control
-CHROMIUMOS_OVERLAY="/usr/local/portage/chromiumos/"
-CHROMIUMOS_CONFIG="${CHROMIUMOS_OVERLAY}/chromeos/config"
-CHROMIUMOS_PROFILES="${CHROMIUMOS_OVERLAY}/profiles"
-BOARD_ETC="${BOARD_ROOT}/etc"
-BOARD_PROFILE="${BOARD_ETC}/portage/profile"
 sudo mkdir -p "${BOARD_ETC}" "${BOARD_PROFILE}"
 
 # Start with the crossdev etc
