setup_board: remove board directory if profile selection failed
BUG=chromium-os:20700
TEST=below
1) setup_board --board=x86-pineview --profile=nonexistant
2) setup_board --board=x86-pineview
(first fails and cleans up after itself, second succeeds)

Change-Id: Ia4dd4e18192d5bdd35ad9b5ebb1488a5a9b842a0
Reviewed-on: https://gerrit.chromium.org/gerrit/11013
Commit-Ready: Zdenek Behan <zbehan@chromium.org>
Reviewed-by: Zdenek Behan <zbehan@chromium.org>
Tested-by: Zdenek Behan <zbehan@chromium.org>

diff --git a/chromeos/scripts/setup_board b/chromeos/scripts/setup_board
--- a/chromeos/scripts/setup_board
+++ b/chromeos/scripts/setup_board
@@ -581,12 +581,17 @@ sudo ln -sf /etc/make.conf.user "${BOARD_ROOT}/etc/make.conf.user"
 # Select the profile to build based on the board and profile passed to
 # setup_board.  The developer can later change profiles by running
 # cros_choose_profile manually.
-cros_choose_profile \
-  --board "${FLAGS_board}" \
-  --build_root "${FLAGS_build_root}" \
-  --board_overlay "${FLAGS_board_overlay}" \
-  --variant "${FLAGS_variant}" \
-  --profile "${FLAGS_profile}"
+if ! cros_choose_profile \
+       --board "${FLAGS_board}" \
+       --build_root "${FLAGS_build_root}" \
+       --board_overlay "${FLAGS_board_overlay}" \
+       --variant "${FLAGS_variant}" \
+       --profile "${FLAGS_profile}"; then
+  error "Selecting profile failed, removing incomplete board directory!"
+  sudo rm -rf "${BOARD_ROOT}"
+  exit 1
+fi
+
 
 for wrapper in 'emerge --root-deps' ebuild eclean equery portageq; do
   generate_wrapper $wrapper
