Add support for using overlay-specific portage profile directories to setup_board
/build/<board>/etc/make.profile will now symlink to <board-overlay>/profiles/base if it exists.  If it does not exist behavior is unchanged.

To preserve existing behavior create <board-overlay>/profiles/base/parent
with the following line:
/usr/local/portage/chromiumos/profiles/default/linux/<arch>/10.0/chromeos
replacing <arch> with the overlays architecture

Change-Id: Ia4e58b20df7e0c16ff0b3231905c19bf666ca437

Added --profile flag to setup_board to support specify different profile directories to link /build/board/etc/make.profile to.

--profile can either be a relative path in overlay/profiles or an absolute
path. If it does not exist that is a fatal error.
If not specified overlay/profiles/base will be used. If that does not exist
it will use /usr/local/portage/chromiumos/chromeos/config/profiles/default/linux/<arch>/profiles/base/

Change-Id: I0395a19d1af2df9ebcc39eb4c038e99ff361e22a

TEST=Ran multiple versions of setup_board with different options and observed that the correct directories were linked (see below)
Setup and built an arm-generic overlay with no changes
Setup, built, burnt and booted a custom overlay using a local profile directory which referenced the previous configuration (/usr/local/portage/chromiumos/profiles/default/linux/x86/10.0/chromeos)
   ./setup_board --board=x86-generic --fast --force --profile=asdf # error'd succesfully
   ./setup_board --board=x86-generic --fast --force --profile=bar  # correctly failed when bar did not exist or was a file
   ./setup_board --board=x86-generic --fast --force --profile=bar # worked when bar was changed to a directory
   ./setup_board --board=x86-generic --fast --force --profile=/asdf/foo # failed correctly, path does not exist
   ./setup_board --board=x86-generic --fast --force --profile=/etc/make.profile  # worked - path existed
   ./setup_board --board=x86-generic --fast --force --profile=bar # empty directory bar created a warning for file 'parent' not existing

BUG=chromium-os:6107

Review URL: http://codereview.chromium.org/3203009

diff --git a/chromeos/scripts/setup_board b/chromeos/scripts/setup_board
--- a/chromeos/scripts/setup_board
+++ b/chromeos/scripts/setup_board
@@ -41,6 +41,8 @@ DEFINE_string kernel_version "2.6.30-r1" \
 DEFINE_boolean default $FLAGS_FALSE \
   "Set board to the default board in your chroot"
 DEFINE_boolean fast ${DEFAULT_FAST} "Call many emerges in parallel"
+DEFINE_string profile "" \
+  "The portage configuration profile to use. Profile must be located in overlay-board/profiles"
 
 # Parse command line flags
 FLAGS "$@" || exit 1
@@ -279,9 +281,37 @@ sudo touch /etc/make.conf.user
 sudo ln -sf /etc/make.globals "${BOARD_ROOT}/etc/make.globals"
 sudo ln -sf /etc/make.conf.user "${BOARD_ROOT}/etc/make.conf.user"
 sudo rm "${BOARD_ROOT}/etc/make.profile"
-sudo ln -sf \
-  "${CHROMIUMOS_PROFILES}/default/linux/${ARCH}/10.0/chromeos/" \
-  "${BOARD_ROOT}/etc/make.profile"
+# The profile directory comes from four possible locations:
+#  * relative profile name from --profile in overlay-board/profiles/<name>
+#  * absolute profile path from --profile
+#  * overlay-board/profiles/base
+#  * ${CHROMIUMOS_PROFILES}/default/linux/${ARCH}/10.0/chromeos
+# If --profile is non-null and does not exist the script will error
+# If none of the directories exist the script will error as well
+PORTAGE_PROFILES_DIR=""
+if [ ! -z "${FLAGS_profile}" ]; then  # profile specified. must exist or we fail
+    if [ -d "${PRIMARY_BOARD_OVERLAY}/profiles/${FLAGS_profile}" ]; then
+	PORTAGE_PROFILES_DIR="${PRIMARY_BOARD_OVERLAY}/profiles/${FLAGS_profile}"
+    elif [ -d "${FLAGS_profile}" ]; then
+	PORTAGE_PROFILES_DIR="${FLAGS_profile}"
+    fi
+    if [ -z "${PORTAGE_PROFILES_DIR}" ]; then
+	error "Profile argument passed as '${FLAGS_profile}' but it does not exist"
+	exit 1
+    fi
+elif [ -d "${PRIMARY_BOARD_OVERLAY}/profiles/base" ]; then 
+    PORTAGE_PROFILES_DIR="${PRIMARY_BOARD_OVERLAY}/profiles/base/"
+else
+    PORTAGE_PROFILES_DIR="${CHROMIUMOS_PROFILES}/default/linux/${ARCH}/10.0/chromeos/"
+fi
+if [ -z "${PORTAGE_PROFILES_DIR}" ]; then
+    error "Profiles directory not found"
+    exit 1
+fi
+sudo ln -sf "${PORTAGE_PROFILES_DIR}" "${BOARD_ROOT}/etc/make.profile"
+if [ ! -f "${PORTAGE_PROFILES_DIR}/parent" ]; then
+    warn "Portage profile directory '${PORTAGE_PROFILES_DIR}' has no file 'parent'.  This likely means your profile directory is invalid and build_packages will fail"
+fi
 
 # Create emerge wrapper
 EMERGE_WRAPPER="/usr/local/bin/emerge-${BOARD_VARIANT}"
