Fix brltty restart flakiness.
Since there can only be one brltty daemon running at a time, make sure to
kill stale ones.  Change the udev trigger to also include 'change' so that
the daemon starts at the appropriate time on boot.
As a minor bonus, stop the daemon from announcing its name and version
when a display is connected.

BUG=chromium:178559
TEST=build a lumpy image, make sure the display is detected on startup and continues to be detected when plugging/unplugging many times.

Change-Id: Id7ad547b4e037f0e7c88c63f162ca1abe0c8eac0
Reviewed-on: https://chromium-review.googlesource.com/169373
Commit-Queue: Peter Lundblad <plundblad@chromium.org>
Tested-by: Peter Lundblad <plundblad@chromium.org>
Reviewed-by: Peter Lundblad <plundblad@chromium.org>

diff --git a/app-accessibility/brltty/files/brltty b/app-accessibility/brltty/files/brltty
--- a/app-accessibility/brltty/files/brltty
+++ b/app-accessibility/brltty/files/brltty
@@ -8,6 +8,34 @@
 
 BRLTTY_RUNDIR=/var/run/brltty
 BRLAPI_SOCKETDIR=/var/lib/BrlAPI
+# The number (0) must be kept in sync with the Host api parameter in
+# brltty.conf.
+BRLAPI_SOCKETFILE="${BRLAPI_SOCKETDIR}/0"
+
+log() {
+  logger -t brltty_udev "$@"
+}
+
+# Kill any stale brltty processes that might be holding on to the
+# BrlAPI socket.  We try hard, because failure to free up the socket will lock
+# the braille user out from the machine!
+kill_stale_brltty() {
+  local SIGTERM_MAX_TRIES=5
+  if fuser -s -k -TERM "${BRLAPI_SOCKETFILE}"; then
+    log "Waiting for stale brltty process to terminate"
+    local i=0
+    while [ ${i} -lt ${SIGTERM_MAX_TRIES} ]; do
+      sleep .1
+      if ! fuser -s -k -TERM "${BRLAPI_SOCKETFILE}"; then
+        return
+      fi
+      : $(( i += 1 ))
+    done
+    log "Sending SIGKILL to stale brltty process"
+    fuser -s -k -KILL "${BRLAPI_SOCKET_FILE}"
+  fi
+}
+kill_stale_brltty
 
 # Ensure that the directories exist and have the right permissions.
 mkdir -p -m 0750 "${BRLTTY_RUNDIR}" "${BRLAPI_SOCKETDIR}"
@@ -18,5 +46,11 @@ chmod 755 "${BRLTTY_RUNDIR}" "${BRLAPI_SOCKETDIR}"
 # brltty group.
 umask 0007
 
+log "Starting brltty, device: ${BRLTTY_DEVICE}, driver: ${BRLTTY_DRIVER}"
+
+# Start brltty in the jail.
+# The options are:
+# - -q: No startup announcement of brltty's version on the braille display.
+# - -E: Get some arguments (driver, device, etc) from the environment.
 exec /sbin/minijail0 -u brltty -g brltty -G -- \
-  /bin/brltty -E -P${BRLTTY_PID_FILE}
+  /bin/brltty -q -E -P${BRLTTY_PID_FILE}
